services:
    powershai-publish-test:
        build: .
        environment:
            HF_API_TOKEN: $TEST_HF_API_TOKEN
            OPENAI_API_KEY: $TEST_OPENAI_API_KEY
            GOOGLE_API_KEY: $TEST_GOOGLE_API_KEY
            CLAUDE_API_KEY: $TEST_CLAUDE_API_KEY
            POWERSHAI_TEST_MODELS: $TEST_POWERSHAI_TEST_MODELS
        command: pwsh -NonInteractive -File ./util/publish-prepare.ps1 -Tests

        
        